# Generated by Django 5.1.6 on 2025-03-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_email', models.EmailField(max_length=100)),
                ('manager_city', models.CharField(max_length=50)),
                ('manager_phone', models.IntegerField()),
                ('manager_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_desc', models.CharField(max_length=200)),
                ('food_category', models.CharField(choices=[('starters', 'starters'), ('Chinese', 'Chinese'), ('indian', 'indian'), ('south indian', 'south indian'), ('main course', 'main course')], max_length=50)),
                ('food_type', models.CharField(choices=[('veg', 'veg'), ('Non-Veg', 'Non-Veg')], max_length=20)),
                ('food_price', models.IntegerField(default=0)),
                ('food_image', models.ImageField(default=None, upload_to='media/')),
            ],
        ),
    ]
