# Generated by Django 5.1.6 on 2025-03-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_type',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non Vegetarian', 'Non Vegetarian')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
