# Generated by Django 5.1.6 on 2025-03-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_menu_food_type_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_category',
            field=models.CharField(choices=[('starters', 'starters'), ('Chinese', 'Chinese'), ('indian', 'indian'), ('snacks', 'snacks'), ('Dessert', 'Dessert'), ('south indian', 'south indian'), ('main course', 'main course')], max_length=50),
        ),
    ]
