# Generated by Django 5.1.6 on 2025-03-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_menu_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food_quantity',
            field=models.IntegerField(default=10),
        ),
    ]
