# Generated by Django 5.1.6 on 2025-03-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered_at',
            field=models.DateTimeField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
