# Generated by Django 5.1.6 on 2025-03-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_orders_ordered_at_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ordered_at',
        ),
    ]
