# Generated by Django 5.1.6 on 2025-03-12 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_orders_ordered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 7, 27, 5, 205280)),
        ),
    ]
