# Generated by Django 5.1.6 on 2025-03-12 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_orders_ordered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ordered_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 7, 28, 11, 549437, tzinfo=datetime.timezone.utc)),
        ),
    ]
