# Generated by Django 5.1.6 on 2025-03-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_orders_ordered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ordered_at',
        ),
    ]
