# Generated by Django 5.1.6 on 2025-03-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_remove_orders_ordered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
    ]
